<?php

declare(strict_types=1);

require_once __DIR__ . '/images.php';

/**
 * Presets de nicho — aplicam textos, seções, look, serviços e imagens.
 */

/**
 * @param array<string, string> $titles slug => título na galeria
 * @return list<array{slug: string, url: string, title: string, description: string, position: int}>
 */
function preset_media_pack(string $id, array $titles): array
{
    $order = [
        'hero' => 2,
        'about' => 3,
        'landing' => 4,
        'corporate' => 5,
        'shop' => 6,
        'maintenance' => 7,
        'integrations' => 8,
        'branding' => 9,
    ];
    $map = [];
    foreach ($titles as $slug => $title) {
        $map[$slug] = [
            'title' => $title,
            'position' => $order[$slug] ?? 50,
            'file' => $slug . '.jpg',
        ];
    }
    return preset_image_rows($id, $map);
}

/**
 * Vitrine da agência Xhybrid (Signature + textos tech).
 */
function preset_xhybrid(): array
{
    return [
        'settings' => [
            'brand_name' => 'Xhybrid',
            'brand_tagline' => 'Sites, manutenção e tecnologia',
            'brand_city' => '',
            'brand_seo_title' => 'Xhybrid — Criação de sites, manutenção e tecnologia',
            'brand_seo_description' => 'Agência Xhybrid: criação de sites, manutenção e tecnologia para empresas. Orçamento rápido pelo WhatsApp.',
            'area_text' => '',
            'urgency_enabled' => '0',
            'urgency_label' => '24h',
            'section_hero' => '1',
            'section_features' => '1',
            'section_works' => '1',
            'section_area' => '0',
            'section_testimonials' => '0',
            'section_faq' => '0',
            'section_cta' => '1',
            'appearance_look' => 'xhybrid-signature',
            'appearance_theme' => 'preto',
            'appearance_font' => 'saas',
            'appearance_layout' => 'soft',
            'appearance_media' => 'classic',
            'whatsapp_message' => 'Olá! Vim pelo site da Xhybrid e quero um orçamento de site.',
            'email' => 'contato@xhybrid.com.br',
            'instagram_url' => 'https://instagram.com/xhybrid',
            'instagram_label' => '@xhybrid — projetos e bastidores',
            'facebook_url' => '',
            'facebook_label' => '',
            'tiktok_url' => '',
            'tiktok_label' => '',
            'address' => '',
            'maps_url' => '',
            'nav_index' => 'Início',
            'nav_sobre' => 'Sobre',
            'nav_galeria' => 'Projetos',
            'nav_contato' => 'Contato',
            'footer_tagline' => 'Agência de criação de sites, manutenção e tecnologia — presença digital profissional para o seu negócio.',
            'footer_link_sobre' => 'Sobre nós',
            'fab_label' => 'Fale conosco',
            'footer_hours_title' => 'Horário de funcionamento',
            'footer_hours_line1' => 'Segunda a sexta: 9h – 18h',
            'footer_hours_line2' => 'Sábado: 9h – 13h',
            'footer_hours_line3' => 'Domingo: fechado',
            'home_badge' => 'Sites & tecnologia',
            'home_hero_title_1' => 'Seu negócio,',
            'home_hero_title_2' => 'online de verdade.',
            'home_hero_text' => 'Somos a Xhybrid — criação de sites, manutenção e tecnologia para empresas que querem presença digital profissional.',
            'home_btn_gallery' => 'Ver projetos',
            'home_btn_quote' => 'Orçamento',
            'home_weave_title' => 'O que fazemos',
            'home_weave_subtitle' => 'Do site institucional à manutenção contínua — tecnologia sob medida para o seu negócio.',
            'home_feat_1_title' => 'Criação de sites',
            'home_feat_1_icon' => 'layout',
            'home_feat_1_text' => 'Landing pages e sites corporativos modernos, rápidos e alinhados à sua marca.',
            'home_feat_2_title' => 'Manutenção',
            'home_feat_2_icon' => 'wrench',
            'home_feat_2_text' => 'Atualizações, backups, performance e correções para o site ficar sempre no ar.',
            'home_feat_3_title' => 'Tecnologia',
            'home_feat_3_icon' => 'cpu',
            'home_feat_3_text' => 'Integrações, automações e melhorias digitais para otimizar o dia a dia.',
            'home_destaques_title' => 'Projetos em destaque',
            'home_destaques_subtitle' => 'Alguns trabalhos de criação e desenvolvimento.',
            'home_destaques_link' => 'Ver portfólio completo',
            'home_cta_title_1' => 'Tem um projeto?',
            'home_cta_title_2' => 'A gente desenvolve.',
            'home_cta_text' => 'Conte o que precisa — site novo, manutenção ou melhoria tecnológica — e montamos a melhor proposta.',
            'home_cta_btn' => 'Orçamento',
            'about_eyebrow' => 'About us',
            'about_title_1' => 'Tecnologia,',
            'about_title_2' => 'com clareza.',
            'about_p1' => 'A Xhybrid nasceu para ajudar empresas a terem presença digital profissional: sites bem feitos, manutenção confiável e tecnologia aplicada ao negócio.',
            'about_p2' => 'Cuidamos do visual, da performance e da operação — do primeiro briefing à publicação, com comunicação direta e prazos claros.',
            'about_p3' => 'Mais do que páginas no ar, entregamos uma base digital sólida para você atender clientes, divulgar serviços e crescer online.',
            'about_btn' => 'Ver projetos',
            'about_stat_1_value' => '100%',
            'about_stat_1_text' => 'Foco em entrega e resultado',
            'about_stat_2_value' => 'Ágil',
            'about_stat_2_text' => 'Processo claro do briefing à publicação',
            'about_stat_3_value' => 'Sob medida',
            'about_stat_3_text' => 'Soluções alinhadas ao seu negócio',
            'gallery_eyebrow' => 'Portfolio',
            'gallery_title' => 'Projetos',
            'gallery_subtitle' => 'Sites e soluções que já entregamos. Toque em uma foto para ampliar.',
            'contact_eyebrow' => 'Get in touch',
            'contact_title' => 'Contato',
            'contact_subtitle' => 'Orçamentos e dúvidas — escolha o canal que preferir.',
            'contact_form_title' => 'Escreva para nós',
            'contact_form_intro' => 'Preencha abaixo e sua mensagem abre direto no seu e-mail.',
            'contact_form_btn' => 'Enviar mensagem',
            'contact_whatsapp_desc' => 'O jeito mais rápido de pedir um orçamento',
            'contact_response_title' => 'Tempo de resposta',
            'contact_response_text' => 'Respondemos em até 1 dia útil',
            'testimonials_title' => 'O que dizem os clientes',
            'testimonial_1_name' => '',
            'testimonial_1_city' => '',
            'testimonial_1_text' => '',
            'testimonial_2_name' => '',
            'testimonial_2_city' => '',
            'testimonial_2_text' => '',
            'testimonial_3_name' => '',
            'testimonial_3_city' => '',
            'testimonial_3_text' => '',
            'faq_title' => 'Dúvidas frequentes',
            'faq_1_q' => '',
            'faq_1_a' => '',
            'faq_2_q' => '',
            'faq_2_a' => '',
            'faq_3_q' => '',
            'faq_3_a' => '',
            'faq_4_q' => '',
            'faq_4_a' => '',
        ],
        'services' => [
            [
                'title' => 'Landing Page',
                'description' => 'Página de captura rápida, objetiva e otimizada para conversão.',
                'image_slug' => 'landing',
                'category' => 'Criação',
                'active' => 1,
            ],
            [
                'title' => 'Site Corporativo',
                'description' => 'Site institucional moderno para apresentar empresa, serviços e contato.',
                'image_slug' => 'corporate',
                'category' => 'Criação',
                'active' => 1,
            ],
            [
                'title' => 'Manutenção contínua',
                'description' => 'Atualizações, backups, performance e suporte para o site ficar no ar.',
                'image_slug' => 'shop',
                'category' => 'Manutenção',
                'active' => 1,
            ],
            [
                'title' => 'Integrações',
                'description' => 'WhatsApp, formulários, CRM e automações alinhadas ao seu fluxo.',
                'image_slug' => 'maintenance',
                'category' => 'Tecnologia',
                'active' => 1,
            ],
        ],
        'images' => preset_media_pack('xhybrid', [
            'hero' => 'Hero — desenvolvimento',
            'about' => 'Equipe Xhybrid',
            'landing' => 'Landing Page',
            'corporate' => 'Site Corporativo',
            'shop' => 'Manutenção Contínua',
            'maintenance' => 'Integrações',
        ]),
    ];
}

function preset_eletricista(): array
{
    return [
        'settings' => [
            'brand_name' => 'Eletricista Pro',
            'brand_tagline' => 'Elétrica residencial e predial',
            'brand_city' => 'Sua cidade',
            'brand_seo_title' => 'Eletricista em Sua cidade — residencial, predial e emergência',
            'brand_seo_description' => 'Serviços elétricos com segurança e agilidade. Orçamento rápido pelo WhatsApp.',
            'area_text' => 'Atendo bairros e cidades da região — consulte disponibilidade.',
            'urgency_enabled' => '1',
            'urgency_label' => '24h',
            'section_hero' => '1',
            'section_features' => '1',
            'section_works' => '1',
            'section_area' => '1',
            'section_testimonials' => '1',
            'section_faq' => '1',
            'section_cta' => '1',
            'appearance_look' => 'azure-blast',
            'appearance_theme' => 'azul',
            'appearance_font' => 'geometric',
            'appearance_layout' => 'frame',
            'appearance_media' => 'media-wide',
            'whatsapp_message' => 'Olá! Preciso de um eletricista. Vim pelo site.',
            'nav_index' => 'Início',
            'nav_sobre' => 'Sobre',
            'nav_galeria' => 'Serviços',
            'nav_contato' => 'Contato',
            'footer_tagline' => 'Elétrica residencial e predial com segurança, clareza e atendimento rápido.',
            'footer_link_sobre' => 'Quem somos',
            'fab_label' => 'Chamar agora',
            'footer_hours_title' => 'Atendimento',
            'footer_hours_line1' => 'Segunda a sábado: 8h – 20h',
            'footer_hours_line2' => 'Emergências: consulte no WhatsApp',
            'footer_hours_line3' => 'Domingo: sob demanda',
            'home_badge' => 'Eletricista profissional',
            'home_hero_title_1' => 'Elétrica segura',
            'home_hero_title_2' => 'quando você precisa.',
            'home_hero_text' => 'Instalações, manutenção e emergências com atendimento ágil. Peça orçamento pelo WhatsApp.',
            'home_btn_gallery' => 'Ver serviços',
            'home_btn_quote' => 'Orçamento',
            'home_weave_title' => 'O que faço',
            'home_weave_subtitle' => 'Soluções elétricas para casa, comércio e condomínio — com padrão de segurança.',
            'home_feat_1_title' => 'Instalações',
            'home_feat_1_icon' => 'bolt',
            'home_feat_1_text' => 'Quadros, tomadas, iluminação e projetos elétricos residenciais e prediais.',
            'home_feat_2_title' => 'Manutenção',
            'home_feat_2_icon' => 'wrench',
            'home_feat_2_text' => 'Revisão, troca de disjuntores, curto-circuito e melhorias de segurança.',
            'home_feat_3_title' => 'Emergência',
            'home_feat_3_icon' => 'plug',
            'home_feat_3_text' => 'Atendimento urgente para falta de energia, cheiro de queimado e riscos.',
            'home_destaques_title' => 'Trabalhos recentes',
            'home_destaques_subtitle' => 'Alguns serviços realizados em campo.',
            'home_destaques_link' => 'Ver mais fotos',
            'home_cta_title_1' => 'Precisa de eletricista?',
            'home_cta_title_2' => 'Chame agora.',
            'home_cta_text' => 'Conte o problema e a região — respondo rápido com orientação e orçamento.',
            'home_cta_btn' => 'Orçamento',
            'about_eyebrow' => 'Sobre',
            'about_title_1' => 'Trabalho sério,',
            'about_title_2' => 'sem improviso.',
            'about_p1' => 'Atendo elétrica residencial e predial com foco em segurança, organização e comunicação clara.',
            'about_p2' => 'Explico o que será feito, materiais necessários e prazo — sem surpresas no meio do serviço.',
            'about_p3' => 'Se precisa de instalação, manutenção ou emergência, fale comigo pelo WhatsApp.',
            'about_btn' => 'Ver serviços',
            'about_stat_1_value' => 'Segurança',
            'about_stat_1_text' => 'Padrão técnico em cada serviço',
            'about_stat_2_value' => 'Ágil',
            'about_stat_2_text' => 'Resposta rápida pelo WhatsApp',
            'about_stat_3_value' => 'Local',
            'about_stat_3_text' => 'Atendimento na sua região',
            'gallery_eyebrow' => 'Serviços',
            'gallery_title' => 'Galeria',
            'gallery_subtitle' => 'Fotos de serviços e instalações. Toque para ampliar.',
            'contact_eyebrow' => 'Contato',
            'contact_title' => 'Fale comigo',
            'contact_subtitle' => 'Orçamento e emergência — WhatsApp é o canal mais rápido.',
            'contact_form_title' => 'Envie uma mensagem',
            'contact_form_intro' => 'Preencha e a mensagem abre no seu e-mail.',
            'contact_form_btn' => 'Enviar',
            'contact_whatsapp_desc' => 'Melhor canal para orçamento e urgência',
            'contact_response_title' => 'Tempo de resposta',
            'contact_response_text' => 'Respondo o mais rápido possível no horário de atendimento',
            'testimonials_title' => 'Clientes satisfeitos',
            'testimonial_1_name' => 'Ana Paula',
            'testimonial_1_city' => 'Centro',
            'testimonial_1_text' => 'Resolveu o quadro elétrico no mesmo dia. Atendimento claro e limpo.',
            'testimonial_2_name' => 'Carlos',
            'testimonial_2_city' => 'Jardins',
            'testimonial_2_text' => 'Instalou a iluminação da casa com muito cuidado. Recomendo.',
            'testimonial_3_name' => 'Marina',
            'testimonial_3_city' => 'Vila Nova',
            'testimonial_3_text' => 'Veio rápido na emergência e explicou tudo sem enrolação.',
            'faq_title' => 'Dúvidas frequentes',
            'faq_1_q' => 'Atende emergência?',
            'faq_1_a' => 'Sim — conforme disponibilidade. Chame no WhatsApp informando o bairro e o problema.',
            'faq_2_q' => 'Emite nota / recibo?',
            'faq_2_a' => 'Combinamos a forma de pagamento e documentação no orçamento.',
            'faq_3_q' => 'Quais bairros atende?',
            'faq_3_a' => 'Atendo a região informada no site. Se estiver em dúvida, pergunte no WhatsApp.',
            'faq_4_q' => 'Tem garantia do serviço?',
            'faq_4_a' => 'Sim, os serviços têm garantia combinada conforme o tipo de trabalho.',
        ],
        'services' => [
            [
                'title' => 'Instalação residencial',
                'description' => 'Tomadas, iluminação, chuveiro e padrões com segurança.',
                'image_slug' => 'landing',
                'category' => 'Residencial',
                'active' => 1,
            ],
            [
                'title' => 'Quadro elétrico',
                'description' => 'Montagem, troca de disjuntores e organização do quadro.',
                'image_slug' => 'corporate',
                'category' => 'Segurança',
                'active' => 1,
            ],
            [
                'title' => 'Manutenção predial',
                'description' => 'Revisão e correções para condomínios e comércios.',
                'image_slug' => 'shop',
                'category' => 'Predial',
                'active' => 1,
            ],
            [
                'title' => 'Emergência',
                'description' => 'Falta de energia, curto-circuito e riscos elétricos.',
                'image_slug' => 'maintenance',
                'category' => 'Urgência',
                'active' => 1,
            ],
            [
                'title' => 'Iluminação LED',
                'description' => 'Projetos e troca para economia e melhor luz.',
                'image_slug' => 'integrations',
                'category' => 'Iluminação',
                'active' => 1,
            ],
            [
                'title' => 'Padrão / entrada',
                'description' => 'Adequação de padrão e entrada de energia.',
                'image_slug' => 'branding',
                'category' => 'Residencial',
                'active' => 1,
            ],
        ],
        'images' => preset_media_pack('eletricista', [
            'hero' => 'Hero — serviços elétricos',
            'about' => 'Instalação profissional',
            'landing' => 'Quadro e medições',
            'corporate' => 'Tomadas e pontos',
            'shop' => 'Iluminação LED',
            'maintenance' => 'Padrão e entrada',
            'integrations' => 'Emergência',
            'branding' => 'Adequação de padrão',
        ]),
    ];
}

function preset_niche_base(array $over): array
{
    $services = $over['_services'] ?? [];
    unset($over['_services']);
    $settings = array_merge([
        'urgency_enabled' => '0',
        'urgency_label' => '24h',
        'section_hero' => '1',
        'section_features' => '1',
        'section_works' => '1',
        'section_area' => '1',
        'section_testimonials' => '1',
        'section_faq' => '1',
        'section_cta' => '1',
        'nav_index' => 'Início',
        'nav_sobre' => 'Sobre',
        'nav_galeria' => 'Serviços',
        'nav_contato' => 'Contato',
        'footer_link_sobre' => 'Quem somos',
        'fab_label' => 'Fale conosco',
        'instagram_url' => '',
        'instagram_label' => '',
        'facebook_url' => '',
        'facebook_label' => '',
        'tiktok_url' => '',
        'tiktok_label' => '',
        'address' => '',
        'maps_url' => '',
        'home_btn_gallery' => 'Ver serviços',
        'home_btn_quote' => 'Orçamento',
        'home_destaques_link' => 'Ver mais',
        'about_btn' => 'Ver serviços',
        'gallery_eyebrow' => 'Serviços',
        'gallery_title' => 'Galeria',
        'contact_form_title' => 'Envie uma mensagem',
        'contact_form_intro' => 'Preencha e enviamos para nossa equipe.',
        'contact_form_btn' => 'Enviar',
        'testimonials_title' => 'Clientes satisfeitos',
        'faq_title' => 'Dúvidas frequentes',
    ], $over);
    return ['settings' => $settings, 'services' => $services];
}

function preset_clinica(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Clínica Vida',
        'brand_tagline' => 'Cuidado humano e atendimento próximo',
        'brand_city' => 'Sua cidade',
        'brand_seo_title' => 'Clínica Vida — consultas e especialidades',
        'brand_seo_description' => 'Clínica com atendimento humanizado. Agende pelo WhatsApp.',
        'area_text' => 'Atendemos pacientes da região — confirme cobertura no WhatsApp.',
        'appearance_look' => 'ocean-vivid',
        'appearance_theme' => 'oceano',
        'appearance_font' => 'soft',
        'appearance_layout' => 'editorial',
        'appearance_media' => 'flip',
        'whatsapp_message' => 'Olá! Quero agendar uma consulta. Vim pelo site.',
        'footer_tagline' => 'Saúde com acolhimento, clareza e compromisso com o paciente.',
        'footer_hours_title' => 'Horário de atendimento',
        'footer_hours_line1' => 'Segunda a sexta: 8h – 18h',
        'footer_hours_line2' => 'Sábado: 8h – 12h',
        'footer_hours_line3' => 'Domingo: fechado',
        'home_badge' => 'Clínica e especialidades',
        'home_hero_title_1' => 'Cuidado de verdade,',
        'home_hero_title_2' => 'perto de você.',
        'home_hero_text' => 'Consultas, exames e acompanhamento com equipe preparada. Agende pelo WhatsApp.',
        'home_weave_title' => 'Como cuidamos',
        'home_weave_subtitle' => 'Atendimento organizado do acolhimento ao retorno.',
        'home_feat_1_title' => 'Consultas',
        'home_feat_1_icon' => 'stethoscope',
        'home_feat_1_text' => 'Avaliação clínica com tempo para ouvir e orientar.',
        'home_feat_2_title' => 'Exames',
        'home_feat_2_icon' => 'cross',
        'home_feat_2_text' => 'Encaminhamento e parceiros para exames com agilidade.',
        'home_feat_3_title' => 'Acompanhamento',
        'home_feat_3_icon' => 'phone',
        'home_feat_3_text' => 'Retornos e planos de cuidado contínuo.',
        'home_destaques_title' => 'Espaço e equipe',
        'home_destaques_subtitle' => 'Ambiente preparado para receber você com conforto.',
        'home_cta_title_1' => 'Quer agendar?',
        'home_cta_title_2' => 'Fale conosco.',
        'home_cta_text' => 'Informe o horário preferido e retornamos com as opções.',
        'home_cta_btn' => 'Orçamento',
        'about_eyebrow' => 'Sobre a clínica',
        'about_title_1' => 'Acolhimento,',
        'about_title_2' => 'com técnica.',
        'about_p1' => 'Nossa clínica une atendimento humanizado e processos claros para cada paciente.',
        'about_p2' => 'Explicamos o próximo passo, prazos e cuidados — sem linguagem confusa.',
        'about_p3' => 'Se precisa marcar consulta ou tirar dúvidas, fale pelo WhatsApp.',
        'about_stat_1_value' => 'Acolhida',
        'about_stat_1_text' => 'Paciente no centro do cuidado',
        'about_stat_2_value' => 'Clareza',
        'about_stat_2_text' => 'Orientação objetiva em cada etapa',
        'about_stat_3_value' => 'Local',
        'about_stat_3_text' => 'Atendimento na sua região',
        'gallery_subtitle' => 'Ambiente, equipe e estrutura. Toque para ampliar.',
        'contact_eyebrow' => 'Agendar',
        'contact_title' => 'Contato',
        'contact_subtitle' => 'Agendamentos e dúvidas — WhatsApp é o canal mais rápido.',
        'contact_whatsapp_desc' => 'Agende ou tire dúvidas com a recepção',
        'contact_response_text' => 'Retornamos no horário de atendimento',
        'testimonial_1_name' => 'Helena',
        'testimonial_1_city' => 'Centro',
        'testimonial_1_text' => 'Atendimento calmo e explicativo. Me senti segura.',
        'testimonial_2_name' => 'Roberto',
        'testimonial_2_city' => 'Jardins',
        'testimonial_2_text' => 'Fácil agendar pelo WhatsApp e horários claros.',
        'testimonial_3_name' => 'Lúcia',
        'testimonial_3_city' => 'Vila Nova',
        'testimonial_3_text' => 'Equipe atenciosa do início ao fim.',
        'faq_1_q' => 'Como agendar?',
        'faq_1_a' => 'Pelo WhatsApp informando especialidade e disponibilidade.',
        'faq_2_q' => 'Aceitam convênio?',
        'faq_2_a' => 'Confirmamos planos e particular no momento do agendamento.',
        'faq_3_q' => 'Tem estacionamento?',
        'faq_3_a' => 'Informamos opções próximas ao confirmar a consulta.',
        'faq_4_q' => 'Posso remarcar?',
        'faq_4_a' => 'Sim — avise com antecedência pelo mesmo canal.',
        '_services' => [
            ['title' => 'Consulta clínica', 'description' => 'Avaliação e orientação personalizada.', 'image_slug' => 'landing', 'category' => 'Consultas', 'active' => 1],
            ['title' => 'Retorno', 'description' => 'Acompanhamento de exames e evolução.', 'image_slug' => 'corporate', 'category' => 'Consultas', 'active' => 1],
            ['title' => 'Check-up', 'description' => 'Rotina preventiva com plano de cuidados.', 'image_slug' => 'shop', 'category' => 'Prevenção', 'active' => 1],
            ['title' => 'Teleorientação', 'description' => 'Dúvidas rápidas quando disponível.', 'image_slug' => 'maintenance', 'category' => 'Online', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('clinica', [
        'hero' => 'Recepção da clínica',
        'about' => 'Equipe de cuidado',
        'landing' => 'Consultório',
        'corporate' => 'Avaliação clínica',
        'shop' => 'Check-up',
        'maintenance' => 'Teleorientação',
    ]);
    return $pack;
}

function preset_restaurante(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Casa do Sabor',
        'brand_tagline' => 'Cozinha afetuosa e mesa bem posta',
        'brand_city' => 'Sua cidade',
        'brand_seo_title' => 'Casa do Sabor — restaurante e reservas',
        'brand_seo_description' => 'Restaurante com pratos autorais. Reserve pelo WhatsApp.',
        'area_text' => 'Salão e delivery na região — consulte bairros no WhatsApp.',
        'urgency_enabled' => '1',
        'urgency_label' => 'Reservas',
        'appearance_look' => 'fire-sunset',
        'appearance_theme' => 'sunset',
        'appearance_font' => 'condensed',
        'appearance_layout' => 'loft',
        'appearance_media' => 'stack-media',
        'whatsapp_message' => 'Olá! Quero fazer uma reserva. Vim pelo site.',
        'nav_galeria' => 'Cardápio',
        'footer_tagline' => 'Ingredientes selecionados, ambiente acolhedor e atendimento próximo.',
        'footer_hours_title' => 'Funcionamento',
        'footer_hours_line1' => 'Terça a domingo: 12h – 15h / 19h – 23h',
        'footer_hours_line2' => 'Segunda: fechado',
        'footer_hours_line3' => 'Delivery: consulte no WhatsApp',
        'home_badge' => 'Restaurante & reservas',
        'home_hero_title_1' => 'Mesa posta,',
        'home_hero_title_2' => 'sabor de casa.',
        'home_hero_text' => 'Pratos sazonais, ambiente aconchegante e reservas fáceis pelo WhatsApp.',
        'home_btn_gallery' => 'Ver cardápio',
        'home_weave_title' => 'A experiência',
        'home_weave_subtitle' => 'Do aperitivo à sobremesa — com ritmo e carinho.',
        'home_feat_1_title' => 'Salão',
        'home_feat_1_icon' => 'utensils',
        'home_feat_1_text' => 'Ambiente para almoço, jantar e ocasiões especiais.',
        'home_feat_2_title' => 'Cardápio',
        'home_feat_2_icon' => 'coffee',
        'home_feat_2_text' => 'Pratos autorais com ingredientes da estação.',
        'home_feat_3_title' => 'Reservas',
        'home_feat_3_icon' => 'phone',
        'home_feat_3_text' => 'Garanta sua mesa pelo WhatsApp em poucos minutos.',
        'home_destaques_title' => 'Pratos em destaque',
        'home_destaques_subtitle' => 'Alguns favoritos da casa.',
        'home_cta_title_1' => 'Quer reservar?',
        'home_cta_title_2' => 'Chame no WhatsApp.',
        'home_cta_text' => 'Informe data, horário e número de pessoas.',
        'home_cta_btn' => 'Reservar',
        'about_eyebrow' => 'Nossa casa',
        'about_title_1' => 'Cozinha viva,',
        'about_title_2' => 'mesa generosa.',
        'about_p1' => 'A Casa do Sabor nasceu para reunir pessoas em torno de comida bem feita.',
        'about_p2' => 'Trabalhamos com fornecedores locais e um cardápio que muda com a estação.',
        'about_p3' => 'Venha almoçar, jantar ou celebrar — reservamos sua mesa com prazer.',
        'about_btn' => 'Ver cardápio',
        'about_stat_1_value' => 'Sazonal',
        'about_stat_1_text' => 'Cardápio alinhado à estação',
        'about_stat_2_value' => 'Acolhedor',
        'about_stat_2_text' => 'Ambiente para estar e conversar',
        'about_stat_3_value' => 'Reserva fácil',
        'about_stat_3_text' => 'WhatsApp direto com a casa',
        'gallery_eyebrow' => 'Cardápio',
        'gallery_title' => 'Pratos',
        'gallery_subtitle' => 'Fotos dos pratos e do salão. Toque para ampliar.',
        'contact_eyebrow' => 'Reservas',
        'contact_title' => 'Fale conosco',
        'contact_subtitle' => 'Reservas, eventos e delivery — WhatsApp é o caminho mais rápido.',
        'contact_whatsapp_desc' => 'Reserve mesa ou peça delivery',
        'testimonial_1_name' => 'Mariana',
        'testimonial_1_city' => 'Centro',
        'testimonial_1_text' => 'Comida excelente e atendimento carinhoso.',
        'testimonial_2_name' => 'Pedro',
        'testimonial_2_city' => 'Bairro Novo',
        'testimonial_2_text' => 'Reserva pelo WhatsApp foi simples e rápida.',
        'testimonial_3_name' => 'Sofia',
        'testimonial_3_city' => 'Praia',
        'testimonial_3_text' => 'Ambiente lindo para jantar a dois.',
        'faq_1_q' => 'Como reservar?',
        'faq_1_a' => 'WhatsApp com data, horário e quantidade de pessoas.',
        'faq_2_q' => 'Tem estacionamento?',
        'faq_2_a' => 'Informamos opções próximas no momento da reserva.',
        'faq_3_q' => 'Aceitam eventos?',
        'faq_3_a' => 'Sim — pergunte disponibilidade e menu especial.',
        'faq_4_q' => 'Fazem delivery?',
        'faq_4_a' => 'Sim em bairros próximos; confirme no WhatsApp.',
        '_services' => [
            ['title' => 'Almoço', 'description' => 'Pratos do dia e clássicos da casa.', 'image_slug' => 'landing', 'category' => 'Salão', 'active' => 1],
            ['title' => 'Jantar', 'description' => 'Menu completo com entradas e sobremesas.', 'image_slug' => 'corporate', 'category' => 'Salão', 'active' => 1],
            ['title' => 'Eventos', 'description' => 'Mesas longas e menus sob consulta.', 'image_slug' => 'shop', 'category' => 'Eventos', 'active' => 1],
            ['title' => 'Delivery', 'description' => 'Seleção para entrega na região.', 'image_slug' => 'maintenance', 'category' => 'Delivery', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('restaurante', [
        'hero' => 'Salão à noite',
        'about' => 'Mesa posta',
        'landing' => 'Prato da casa',
        'corporate' => 'Jantar',
        'shop' => 'Sobremesas',
        'maintenance' => 'Delivery',
    ]);
    return $pack;
}

function preset_advocacia(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Almeida Advocacia',
        'brand_tagline' => 'Orientação jurídica clara e estratégica',
        'brand_city' => 'Sua cidade',
        'brand_seo_title' => 'Almeida Advocacia — consultoria e contencioso',
        'brand_seo_description' => 'Escritório de advocacia com atendimento objetivo. Fale pelo WhatsApp.',
        'area_text' => 'Atendimento presencial e online — confirme sua comarca.',
        'appearance_look' => 'navy-depth',
        'appearance_theme' => 'midnight',
        'appearance_font' => 'geometric',
        'appearance_layout' => 'magazine',
        'appearance_media' => 'about-flip',
        'whatsapp_message' => 'Olá! Preciso de orientação jurídica. Vim pelo site.',
        'nav_galeria' => 'Áreas',
        'footer_tagline' => 'Advocacia com escuta, estratégia e comunicação transparente.',
        'footer_hours_title' => 'Atendimento',
        'footer_hours_line1' => 'Segunda a sexta: 9h – 18h',
        'footer_hours_line2' => 'Plantão: sob combinação',
        'footer_hours_line3' => 'Sábado e domingo: fechado',
        'home_badge' => 'Advocacia & consultoria',
        'home_hero_title_1' => 'Orientação jurídica',
        'home_hero_title_2' => 'com clareza.',
        'home_hero_text' => 'Análise do seu caso, próximos passos e acompanhamento — com linguagem acessível.',
        'home_btn_gallery' => 'Ver áreas',
        'home_weave_title' => 'Como atuamos',
        'home_weave_subtitle' => 'Diagnóstico, estratégia e execução com comunicação direta.',
        'home_feat_1_title' => 'Consultoria',
        'home_feat_1_icon' => 'scale',
        'home_feat_1_text' => 'Análise preventiva de contratos e riscos.',
        'home_feat_2_title' => 'Contencioso',
        'home_feat_2_icon' => 'gavel',
        'home_feat_2_text' => 'Defesa e acompanhamento processual.',
        'home_feat_3_title' => 'Acordos',
        'home_feat_3_icon' => 'briefcase',
        'home_feat_3_text' => 'Negociação com foco em resultado e prazo.',
        'home_destaques_title' => 'Áreas de atuação',
        'home_destaques_subtitle' => 'Especialidades disponíveis no escritório.',
        'home_cta_title_1' => 'Precisa de orientação?',
        'home_cta_title_2' => 'Fale com a equipe.',
        'home_cta_text' => 'Conte o contexto em poucas linhas — retornamos com o próximo passo.',
        'home_cta_btn' => 'Orçamento',
        'about_eyebrow' => 'Escritório',
        'about_title_1' => 'Estratégia,',
        'about_title_2' => 'sem enrolação.',
        'about_p1' => 'Atuamos com escuta ativa e planos jurídicos objetivos para pessoas e empresas.',
        'about_p2' => 'Explicamos riscos, prazos e caminhos possíveis antes de qualquer decisão.',
        'about_p3' => 'Se precisa de consultoria ou defesa, inicie pelo WhatsApp.',
        'about_btn' => 'Ver áreas',
        'about_stat_1_value' => 'Clareza',
        'about_stat_1_text' => 'Linguagem acessível em cada etapa',
        'about_stat_2_value' => 'Foco',
        'about_stat_2_text' => 'Estratégia alinhada ao seu objetivo',
        'about_stat_3_value' => 'Sigilo',
        'about_stat_3_text' => 'Confidencialidade profissional',
        'gallery_eyebrow' => 'Áreas',
        'gallery_title' => 'Atuação',
        'gallery_subtitle' => 'Especialidades e materiais. Toque para ampliar.',
        'contact_eyebrow' => 'Atendimento',
        'contact_title' => 'Contato',
        'contact_subtitle' => 'Primeira conversa e agendamento — WhatsApp ou formulário.',
        'contact_whatsapp_desc' => 'Canal direto com a equipe',
        'testimonial_1_name' => 'Empresa Alfa',
        'testimonial_1_city' => 'SP',
        'testimonial_1_text' => 'Consultoria objetiva e prazos cumpridos.',
        'testimonial_2_name' => 'Juliana',
        'testimonial_2_city' => 'Campinas',
        'testimonial_2_text' => 'Explicaram tudo com clareza do início ao fim.',
        'testimonial_3_name' => 'Grupo Norte',
        'testimonial_3_city' => 'Interior',
        'testimonial_3_text' => 'Negociação bem conduzida e comunicação constante.',
        'faq_1_q' => 'Como começa o atendimento?',
        'faq_1_a' => 'Briefing pelo WhatsApp e agendamento de reunião.',
        'faq_2_q' => 'Atendem online?',
        'faq_2_a' => 'Sim, videoconferência quando fizer sentido.',
        'faq_3_q' => 'Como funciona honorários?',
        'faq_3_a' => 'Apresentamos proposta após entender o caso.',
        'faq_4_q' => 'Quais áreas cobrem?',
        'faq_4_a' => 'Veja a página de áreas ou pergunte no WhatsApp.',
        '_services' => [
            ['title' => 'Cível', 'description' => 'Contratos, responsabilidade e disputas.', 'image_slug' => 'landing', 'category' => 'Áreas', 'active' => 1],
            ['title' => 'Empresarial', 'description' => 'Societário, compliance e negociações.', 'image_slug' => 'corporate', 'category' => 'Áreas', 'active' => 1],
            ['title' => 'Trabalhista', 'description' => 'Consultivo e contencioso trabalhista.', 'image_slug' => 'shop', 'category' => 'Áreas', 'active' => 1],
            ['title' => 'Família', 'description' => 'Acordos e processos com mediação.', 'image_slug' => 'maintenance', 'category' => 'Áreas', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('advocacia', [
        'hero' => 'Escritório',
        'about' => 'Advogado',
        'landing' => 'Consultoria',
        'corporate' => 'Contratos',
        'shop' => 'Reuniões',
        'maintenance' => 'Acordos',
    ]);
    return $pack;
}

function preset_limpeza(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Limpeza Clara',
        'brand_tagline' => 'Residencial e comercial com padrão alto',
        'brand_city' => 'Sua cidade',
        'brand_seo_title' => 'Limpeza Clara — limpeza residencial e comercial',
        'brand_seo_description' => 'Limpeza profissional para casas e empresas. Orçamento rápido pelo WhatsApp.',
        'area_text' => 'Atendemos casas, apartamentos e escritórios na região — confirme no WhatsApp.',
        'urgency_enabled' => '1',
        'urgency_label' => 'Agenda',
        'appearance_look' => 'teal-rush',
        'appearance_theme' => 'teal',
        'appearance_font' => 'soft',
        'appearance_layout' => 'soft',
        'appearance_media' => 'classic',
        'whatsapp_message' => 'Olá! Quero orçamento de limpeza. Vim pelo site.',
        'nav_galeria' => 'Serviços',
        'footer_tagline' => 'Ambientes limpos, seguros e bem cuidados — com equipe treinada e produtos adequados.',
        'footer_hours_title' => 'Horário',
        'footer_hours_line1' => 'Segunda a sábado: 7h – 18h',
        'footer_hours_line2' => 'Domingo: sob consulta',
        'footer_hours_line3' => 'Plantões para empresas: combine no WhatsApp',
        'home_badge' => 'Limpeza profissional',
        'home_hero_title_1' => 'Ambiente limpo,',
        'home_hero_title_2' => 'sem preocupação.',
        'home_hero_text' => 'Limpeza residencial e comercial com padrões claros, pontualidade e acabamento caprichado.',
        'home_btn_gallery' => 'Ver serviços',
        'home_weave_title' => 'O que limpamos',
        'home_weave_subtitle' => 'Do dia a dia à limpeza pesada — com checklist e qualidade.',
        'home_feat_1_title' => 'Residencial',
        'home_feat_1_icon' => 'sparkles',
        'home_feat_1_text' => 'Casas e apartamentos com foco em detalhes e organização.',
        'home_feat_2_title' => 'Comercial',
        'home_feat_2_icon' => 'building',
        'home_feat_2_text' => 'Escritórios e lojas com rotina que não atrapalha o expediente.',
        'home_feat_3_title' => 'Produtos',
        'home_feat_3_icon' => 'droplets',
        'home_feat_3_text' => 'Materiais adequados para cada superfície e higiene segura.',
        'home_destaques_title' => 'Antes e depois do cuidado',
        'home_destaques_subtitle' => 'Alguns ambientes que deixamos impecáveis.',
        'home_cta_title_1' => 'Quer orçamento?',
        'home_cta_title_2' => 'Chame no WhatsApp.',
        'home_cta_text' => 'Informe metragem, tipo de imóvel e frequência desejada.',
        'home_cta_btn' => 'Orçamento',
        'about_eyebrow' => 'Quem somos',
        'about_title_1' => 'Limpeza com',
        'about_title_2' => 'padrão e confiança.',
        'about_p1' => 'A Limpeza Clara nasceu para entregar ambientes higienizados sem você precisar acompanhar cada passo.',
        'about_p2' => 'Trabalhamos com checklist, horários combinados e comunicação direta pelo WhatsApp.',
        'about_p3' => 'Seja residência ou empresa, montamos a rotina que cabe na sua rotina.',
        'about_stat_1_value' => 'Checklist',
        'about_stat_1_text' => 'Padrão claro em cada visita',
        'about_stat_2_value' => 'Pontual',
        'about_stat_2_text' => 'Horários combinados e cumpridos',
        'about_stat_3_value' => 'Sob medida',
        'about_stat_3_text' => 'Frequência semanal, quinzenal ou avulsa',
        'gallery_subtitle' => 'Ambientes e serviços. Toque para ampliar.',
        'contact_eyebrow' => 'Orçamento',
        'contact_title' => 'Contato',
        'contact_subtitle' => 'Peça orçamento com metragem e tipo de limpeza.',
        'contact_whatsapp_desc' => 'Resposta rápida para agendar sua limpeza',
        'contact_response_text' => 'Retornamos no mesmo dia útil',
        'testimonial_1_name' => 'Camila',
        'testimonial_1_city' => 'Centro',
        'testimonial_1_text' => 'Apartamento impecável e equipe educada. Virei cliente fixa.',
        'testimonial_2_name' => 'Escritório Norte',
        'testimonial_2_city' => 'Empresarial',
        'testimonial_2_text' => 'Limpeza comercial sem atrapalhar o expediente.',
        'testimonial_3_name' => 'Paulo',
        'testimonial_3_city' => 'Jardins',
        'testimonial_3_text' => 'Pós-obra ficou perfeito. Recomendo.',
        'faq_1_q' => 'Vocês levam produtos?',
        'faq_1_a' => 'Sim — ou usamos os seus, se preferir. Combinamos no orçamento.',
        'faq_2_q' => 'Fazem limpeza pós-obra?',
        'faq_2_a' => 'Sim. Informe o estágio da obra para dimensionarmos a equipe.',
        'faq_3_q' => 'Atendem empresas?',
        'faq_3_a' => 'Sim, com rotina diária, semanal ou sob demanda.',
        'faq_4_q' => 'Como precificar?',
        'faq_4_a' => 'Por metragem, tipo de limpeza e frequência. Orçamento no WhatsApp.',
        '_services' => [
            ['title' => 'Limpeza residencial', 'description' => 'Casa ou apartamento com checklist completo.', 'image_slug' => 'landing', 'category' => 'Residencial', 'active' => 1],
            ['title' => 'Banheiros e áreas molhadas', 'description' => 'Higienização profunda de boxes, pisos e louças.', 'image_slug' => 'corporate', 'category' => 'Residencial', 'active' => 1],
            ['title' => 'Limpeza comercial', 'description' => 'Escritórios e lojas com rotina discreta.', 'image_slug' => 'shop', 'category' => 'Comercial', 'active' => 1],
            ['title' => 'Kit e materiais', 'description' => 'Equipamentos e produtos para um acabamento profissional.', 'image_slug' => 'maintenance', 'category' => 'Padrão', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('limpeza', [
        'hero' => 'Limpeza residencial',
        'about' => 'Equipe de limpeza',
        'landing' => 'Cozinha impecável',
        'corporate' => 'Banheiro higienizado',
        'shop' => 'Escritório limpo',
        'maintenance' => 'Kit profissional',
    ]);
    return $pack;
}

function preset_locacao(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Rota Fácil',
        'brand_tagline' => 'Locação de veículos para o seu dia a dia',
        'brand_city' => 'Sua cidade',
        'brand_seo_title' => 'Rota Fácil — locação de carros e utilitários',
        'brand_seo_description' => 'Aluguel de veículos com frota revisada. Reserve pelo WhatsApp.',
        'area_text' => 'Retirada na loja e entrega sob consulta na região.',
        'urgency_enabled' => '1',
        'urgency_label' => 'Reservas',
        'appearance_look' => 'azure-blast',
        'appearance_theme' => 'azul',
        'appearance_font' => 'saas',
        'appearance_layout' => 'frame',
        'appearance_media' => 'media-wide',
        'whatsapp_message' => 'Olá! Quero cotar a locação de um veículo. Vim pelo site.',
        'nav_galeria' => 'Frota',
        'footer_tagline' => 'Frota revisada, atendimento claro e reserva rápida pelo WhatsApp.',
        'footer_hours_title' => 'Horário da loja',
        'footer_hours_line1' => 'Segunda a sexta: 8h – 18h',
        'footer_hours_line2' => 'Sábado: 8h – 13h',
        'footer_hours_line3' => 'Domingo: fechado',
        'home_badge' => 'Locação de veículos',
        'home_hero_title_1' => 'Seu carro pronto,',
        'home_hero_title_2' => 'quando você precisa.',
        'home_hero_text' => 'Compactos, SUVs e utilitários revisados — reserve pelo WhatsApp com agilidade.',
        'home_btn_gallery' => 'Ver frota',
        'home_weave_title' => 'Como funciona',
        'home_weave_subtitle' => 'Escolha o modelo, combine datas e retire com documentação simples.',
        'home_feat_1_title' => 'Frota revisada',
        'home_feat_1_icon' => 'car',
        'home_feat_1_text' => 'Veículos higienizados e com manutenção em dia.',
        'home_feat_2_title' => 'Categorias',
        'home_feat_2_icon' => 'truck',
        'home_feat_2_text' => 'Do compacto ao utilitário — sobe a categoria conforme a viagem.',
        'home_feat_3_title' => 'Reserva fácil',
        'home_feat_3_icon' => 'phone',
        'home_feat_3_text' => 'Cotação e confirmação rápidas pelo WhatsApp.',
        'home_destaques_title' => 'Frota em destaque',
        'home_destaques_subtitle' => 'Modelos disponíveis para locação.',
        'home_cta_title_1' => 'Quer reservar?',
        'home_cta_title_2' => 'Fale conosco.',
        'home_cta_text' => 'Informe datas, categoria e se precisa de motorista ou entrega.',
        'home_cta_btn' => 'Orçamento',
        'about_eyebrow' => 'A locadora',
        'about_title_1' => 'Mobilidade com',
        'about_title_2' => 'transparência.',
        'about_p1' => 'A Rota Fácil oferece locação de veículos com atendimento direto e frota cuidada.',
        'about_p2' => 'Explicamos diárias, caução e cobertura sem letras miúdas escondidas.',
        'about_p3' => 'Ideal para viagem, trabalho ou substituição do carro particular.',
        'about_stat_1_value' => 'Frota',
        'about_stat_1_text' => 'Modelos para cidade e estrada',
        'about_stat_2_value' => 'Revisão',
        'about_stat_2_text' => 'Manutenção e higienização constantes',
        'about_stat_3_value' => 'Ágil',
        'about_stat_3_text' => 'Reserva pelo WhatsApp',
        'gallery_eyebrow' => 'Frota',
        'gallery_title' => 'Veículos',
        'gallery_subtitle' => 'Categorias disponíveis. Toque para ampliar.',
        'contact_eyebrow' => 'Reservas',
        'contact_title' => 'Contato',
        'contact_subtitle' => 'Peça cotação com datas e categoria desejada.',
        'contact_whatsapp_desc' => 'Reserve ou tire dúvidas sobre a frota',
        'contact_response_text' => 'Retorno rápido em horário comercial',
        'testimonial_1_name' => 'André',
        'testimonial_1_city' => 'Centro',
        'testimonial_1_text' => 'Carro limpo, entrega no horário e preço justo.',
        'testimonial_2_name' => 'Empresa Delta',
        'testimonial_2_city' => 'Industrial',
        'testimonial_2_text' => 'Locamos utilitário para obra — processo simples.',
        'testimonial_3_name' => 'Fernanda',
        'testimonial_3_city' => 'Praia',
        'testimonial_3_text' => 'SUV impecável para o fim de semana.',
        'faq_1_q' => 'Quais documentos preciso?',
        'faq_1_a' => 'CNH válida e documento com foto. Detalhamos no WhatsApp.',
        'faq_2_q' => 'Tem caução?',
        'faq_2_a' => 'Sim, conforme categoria — valores transparentes na cotação.',
        'faq_3_q' => 'Posso devolver em outra cidade?',
        'faq_3_a' => 'Sob consulta. Informe origem e destino na reserva.',
        'faq_4_q' => 'Inclui seguro?',
        'faq_4_a' => 'Coberturas e franquias são apresentadas antes da confirmação.',
        '_services' => [
            ['title' => 'Compacto', 'description' => 'Ideal para cidade e economia de combustível.', 'image_slug' => 'landing', 'category' => 'Frota', 'active' => 1],
            ['title' => 'SUV', 'description' => 'Conforto para família e viagens.', 'image_slug' => 'corporate', 'category' => 'Frota', 'active' => 1],
            ['title' => 'Sedan', 'description' => 'Espaço e conforto para o dia a dia executivo.', 'image_slug' => 'shop', 'category' => 'Frota', 'active' => 1],
            ['title' => 'Utilitário', 'description' => 'Pickup para carga e trabalho.', 'image_slug' => 'maintenance', 'category' => 'Frota', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('locacao', [
        'hero' => 'Frota pronta',
        'about' => 'Atendimento na retirada',
        'landing' => 'Compacto',
        'corporate' => 'SUV',
        'shop' => 'Sedan',
        'maintenance' => 'Utilitário',
    ]);
    return $pack;
}

function preset_function_map(): array
{
    return [
        'xhybrid' => 'preset_xhybrid',
        'eletricista' => 'preset_eletricista',
        'clinica' => 'preset_clinica',
        'restaurante' => 'preset_restaurante',
        'advocacia' => 'preset_advocacia',
        'limpeza' => 'preset_limpeza',
        'locacao' => 'preset_locacao',
        'dentista' => 'preset_dentista',
        'estetica' => 'preset_estetica',
        'salao' => 'preset_salao',
        'contador' => 'preset_contador',
        'imobiliaria' => 'preset_imobiliaria',
        'pet' => 'preset_pet',
        'academia' => 'preset_academia',
        'oficina' => 'preset_oficina',
        'arquitetura' => 'preset_arquitetura',
        'consultoria' => 'preset_consultoria',
    ];
}

function preset_dentista(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Consultório Odontológico',
        'brand_tagline' => 'Sorriso saudável com atendimento próximo',
        'brand_seo_title' => 'Dentista — consultas e tratamentos',
        'brand_seo_description' => 'Clínica odontológica. Agende avaliação pelo WhatsApp.',
        'appearance_look' => 'ocean-vivid',
        'appearance_theme' => 'oceano',
        'appearance_font' => 'soft',
        'appearance_layout' => 'editorial',
        'appearance_media' => 'flip',
        'whatsapp_message' => 'Olá! Quero agendar uma avaliação odontológica.',
        'home_badge' => 'Odontologia',
        'home_hero_title_1' => 'Cuidado com o',
        'home_hero_title_2' => 'seu sorriso.',
        'home_hero_text' => 'Consultas, limpeza, clareamento e tratamentos com equipe preparada.',
        'home_feat_1_title' => 'Avaliação',
        'home_feat_1_icon' => 'stethoscope',
        'home_feat_1_text' => 'Diagnóstico claro e plano de tratamento sem surpresas.',
        'home_feat_2_title' => 'Limpeza',
        'home_feat_2_icon' => 'sparkles',
        'home_feat_2_text' => 'Profilaxia e prevenção para manter a saúde bucal.',
        'home_feat_3_title' => 'Estética',
        'home_feat_3_icon' => 'star',
        'home_feat_3_text' => 'Clareamento e restaurações com resultado natural.',
        'home_cta_title_1' => 'Quer agendar?',
        'home_cta_title_2' => 'Fale conosco.',
        'about_title_1' => 'Odontologia',
        'about_title_2' => 'com acolhimento.',
        '_services' => [
            ['title' => 'Consulta', 'description' => 'Avaliação completa e orientação.', 'image_slug' => 'landing', 'category' => 'Clínica', 'active' => 1],
            ['title' => 'Limpeza', 'description' => 'Profilaxia e prevenção.', 'image_slug' => 'corporate', 'category' => 'Clínica', 'active' => 1],
            ['title' => 'Clareamento', 'description' => 'Protocolos seguros para um sorriso mais branco.', 'image_slug' => 'shop', 'category' => 'Estética', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('clinica', [
        'hero' => 'Consultório', 'about' => 'Equipe', 'landing' => 'Consulta', 'corporate' => 'Limpeza', 'shop' => 'Clareamento', 'maintenance' => 'Ortodontia',
    ]);
    return $pack;
}

function preset_estetica(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Estética & Bem-estar',
        'brand_tagline' => 'Beleza com cuidado e naturalidade',
        'brand_seo_title' => 'Estética — tratamentos faciais e corporais',
        'appearance_look' => 'ivory-soft',
        'appearance_theme' => 'gelo',
        'appearance_font' => 'rounded',
        'appearance_layout' => 'pill',
        'appearance_media' => 'flip',
        'whatsapp_message' => 'Olá! Quero saber sobre tratamentos estéticos.',
        'home_badge' => 'Estética',
        'home_hero_title_1' => 'Cuidado que',
        'home_hero_title_2' => 'realça você.',
        'home_hero_text' => 'Procedimentos faciais e corporais com atendimento personalizado.',
        'home_feat_1_title' => 'Facial',
        'home_feat_1_icon' => 'sparkles',
        'home_feat_1_text' => 'Limpeza, peeling e protocolos anti-idade.',
        'home_feat_2_title' => 'Corporal',
        'home_feat_2_icon' => 'heart',
        'home_feat_2_text' => 'Modelagem e bem-estar com acompanhamento.',
        'home_feat_3_title' => 'Agenda',
        'home_feat_3_icon' => 'calendar',
        'home_feat_3_text' => 'Horários flexíveis pelo WhatsApp.',
        '_services' => [
            ['title' => 'Limpeza de pele', 'description' => 'Protocolo completo para revitalizar a pele.', 'image_slug' => 'landing', 'category' => 'Facial', 'active' => 1],
            ['title' => 'Peeling', 'description' => 'Renovação com orientação profissional.', 'image_slug' => 'corporate', 'category' => 'Facial', 'active' => 1],
            ['title' => 'Corporal', 'description' => 'Tratamentos sob medida.', 'image_slug' => 'shop', 'category' => 'Corpo', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('clinica', [
        'hero' => 'Espaço', 'about' => 'Atendimento', 'landing' => 'Facial', 'corporate' => 'Corporal', 'shop' => 'Resultados', 'maintenance' => 'Cuidados',
    ]);
    return $pack;
}

function preset_salao(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Salão & Barbearia',
        'brand_tagline' => 'Corte, cor e estilo',
        'brand_seo_title' => 'Salão de beleza — corte e coloração',
        'appearance_look' => 'warm-studio',
        'appearance_theme' => 'marrom-claro',
        'appearance_font' => 'classic',
        'appearance_layout' => 'loft',
        'appearance_media' => 'center',
        'whatsapp_message' => 'Olá! Quero agendar horário no salão.',
        'home_badge' => 'Beleza',
        'home_hero_title_1' => 'Seu visual,',
        'home_hero_title_2' => 'do seu jeito.',
        'home_hero_text' => 'Cortes, coloração e barba com profissionais experientes.',
        'home_feat_1_title' => 'Corte',
        'home_feat_1_icon' => 'scissors',
        'home_feat_1_text' => 'Masculino e feminino com acabamento impecável.',
        'home_feat_2_title' => 'Cor',
        'home_feat_2_icon' => 'sparkles',
        'home_feat_2_text' => 'Coloração e mechas com produtos de qualidade.',
        'home_feat_3_title' => 'Barba',
        'home_feat_3_icon' => 'user',
        'home_feat_3_text' => 'Design e cuidados para barba e bigode.',
        '_services' => [
            ['title' => 'Corte', 'description' => 'Corte personalizado.', 'image_slug' => 'landing', 'category' => 'Salão', 'active' => 1],
            ['title' => 'Coloração', 'description' => 'Cor e mechas.', 'image_slug' => 'corporate', 'category' => 'Salão', 'active' => 1],
            ['title' => 'Barba', 'description' => 'Acabamento e design.', 'image_slug' => 'shop', 'category' => 'Barbearia', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('xhybrid', [
        'hero' => 'Salão', 'about' => 'Equipe', 'landing' => 'Corte', 'corporate' => 'Cor', 'shop' => 'Barba', 'maintenance' => 'Ambiente',
    ]);
    return $pack;
}

function preset_contador(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Contabilidade',
        'brand_tagline' => 'Números claros para o seu negócio',
        'brand_seo_title' => 'Contador — contabilidade e fiscal',
        'appearance_look' => 'sharp-saas',
        'appearance_theme' => 'graphite',
        'appearance_font' => 'saas',
        'appearance_layout' => 'sharp',
        'appearance_media' => 'media-wide',
        'whatsapp_message' => 'Olá! Preciso de suporte contábil.',
        'home_badge' => 'Contabilidade',
        'home_hero_title_1' => 'Contabilidade',
        'home_hero_title_2' => 'sem complicação.',
        'home_hero_text' => 'Abertura, fiscal, folha e consultoria para MEI e empresas.',
        'home_feat_1_title' => 'Fiscal',
        'home_feat_1_icon' => 'file',
        'home_feat_1_text' => 'Obrigações em dia com orientação clara.',
        'home_feat_2_title' => 'Folha',
        'home_feat_2_icon' => 'users',
        'home_feat_2_text' => 'Departamento pessoal organizado.',
        'home_feat_3_title' => 'Consultoria',
        'home_feat_3_icon' => 'chart',
        'home_feat_3_text' => 'Decisões com base em números reais.',
        '_services' => [
            ['title' => 'Abertura de empresa', 'description' => 'MEI e sociedades.', 'image_slug' => 'landing', 'category' => 'Contábil', 'active' => 1],
            ['title' => 'Fiscal', 'description' => 'Impostos e obrigações.', 'image_slug' => 'corporate', 'category' => 'Contábil', 'active' => 1],
            ['title' => 'Folha', 'description' => 'Admissão e encargos.', 'image_slug' => 'shop', 'category' => 'RH', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('advocacia', [
        'hero' => 'Escritório', 'about' => 'Equipe', 'landing' => 'Fiscal', 'corporate' => 'Consultoria', 'shop' => 'Relatórios', 'maintenance' => 'Atendimento',
    ]);
    return $pack;
}

function preset_imobiliaria(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Imobiliária',
        'brand_tagline' => 'Imóveis com transparência',
        'brand_seo_title' => 'Imobiliária — compra, venda e aluguel',
        'appearance_look' => 'navy-depth',
        'appearance_theme' => 'midnight',
        'appearance_font' => 'geometric',
        'appearance_layout' => 'magazine',
        'appearance_media' => 'about-flip',
        'whatsapp_message' => 'Olá! Quero informações sobre imóveis.',
        'home_badge' => 'Imóveis',
        'home_hero_title_1' => 'O imóvel certo,',
        'home_hero_title_2' => 'com segurança.',
        'home_hero_text' => 'Compra, venda e locação com acompanhamento completo.',
        'home_feat_1_title' => 'Venda',
        'home_feat_1_icon' => 'home',
        'home_feat_1_text' => 'Anúncio e negociação com suporte.',
        'home_feat_2_title' => 'Aluguel',
        'home_feat_2_icon' => 'key',
        'home_feat_2_text' => 'Locação residencial e comercial.',
        'home_feat_3_title' => 'Avaliação',
        'home_feat_3_icon' => 'search',
        'home_feat_3_text' => 'Valor de mercado com clareza.',
        '_services' => [
            ['title' => 'Venda', 'description' => 'Intermediação completa.', 'image_slug' => 'landing', 'category' => 'Imóveis', 'active' => 1],
            ['title' => 'Aluguel', 'description' => 'Locação e contratos.', 'image_slug' => 'corporate', 'category' => 'Imóveis', 'active' => 1],
            ['title' => 'Avaliação', 'description' => 'Laudo e orientação.', 'image_slug' => 'shop', 'category' => 'Imóveis', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('locacao', [
        'hero' => 'Fachada', 'about' => 'Corretores', 'landing' => 'Apartamento', 'corporate' => 'Casa', 'shop' => 'Comercial', 'maintenance' => 'Chaves',
    ]);
    return $pack;
}

function preset_pet(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Pet Shop & Clínica',
        'brand_tagline' => 'Cuidado para quem você ama',
        'brand_seo_title' => 'Pet shop — banho, tosa e veterinário',
        'appearance_look' => 'teal-rush',
        'appearance_theme' => 'teal',
        'appearance_font' => 'rounded',
        'appearance_layout' => 'soft',
        'appearance_media' => 'classic',
        'whatsapp_message' => 'Olá! Quero agendar banho/tosa ou consulta pet.',
        'home_badge' => 'Pets',
        'home_hero_title_1' => 'Seu pet,',
        'home_hero_title_2' => 'bem cuidado.',
        'home_hero_text' => 'Banho, tosa, produtos e atendimento veterinário.',
        'home_feat_1_title' => 'Banho e tosa',
        'home_feat_1_icon' => 'heart',
        'home_feat_1_text' => 'Higiene com carinho e segurança.',
        'home_feat_2_title' => 'Veterinário',
        'home_feat_2_icon' => 'cross',
        'home_feat_2_text' => 'Consultas e vacinas.',
        'home_feat_3_title' => 'Loja',
        'home_feat_3_icon' => 'bag',
        'home_feat_3_text' => 'Ração e acessórios.',
        '_services' => [
            ['title' => 'Banho e tosa', 'description' => 'Higiene completa.', 'image_slug' => 'landing', 'category' => 'Pet', 'active' => 1],
            ['title' => 'Consulta', 'description' => 'Atendimento veterinário.', 'image_slug' => 'corporate', 'category' => 'Clínica', 'active' => 1],
            ['title' => 'Produtos', 'description' => 'Ração e acessórios.', 'image_slug' => 'shop', 'category' => 'Loja', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('clinica', [
        'hero' => 'Pet', 'about' => 'Equipe', 'landing' => 'Banho', 'corporate' => 'Consulta', 'shop' => 'Loja', 'maintenance' => 'Acessórios',
    ]);
    return $pack;
}

function preset_academia(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Academia & Personal',
        'brand_tagline' => 'Treino com resultado',
        'brand_seo_title' => 'Academia — musculação e personal trainer',
        'appearance_look' => 'obsidian',
        'appearance_theme' => 'preto',
        'appearance_font' => 'display',
        'appearance_layout' => 'frame',
        'appearance_media' => 'copy-wide',
        'whatsapp_message' => 'Olá! Quero informações sobre planos e treinos.',
        'home_badge' => 'Fitness',
        'home_hero_title_1' => 'Treine com',
        'home_hero_title_2' => 'propósito.',
        'home_hero_text' => 'Musculação, funcional e personal com acompanhamento.',
        'home_feat_1_title' => 'Musculação',
        'home_feat_1_icon' => 'zap',
        'home_feat_1_text' => 'Equipamentos e treinos progressivos.',
        'home_feat_2_title' => 'Personal',
        'home_feat_2_icon' => 'user',
        'home_feat_2_text' => 'Plano individual sob medida.',
        'home_feat_3_title' => 'Aulas',
        'home_feat_3_icon' => 'users',
        'home_feat_3_text' => 'Funcional e coletivas.',
        '_services' => [
            ['title' => 'Plano mensal', 'description' => 'Acesso à musculação.', 'image_slug' => 'landing', 'category' => 'Planos', 'active' => 1],
            ['title' => 'Personal', 'description' => 'Treino individual.', 'image_slug' => 'corporate', 'category' => 'Treino', 'active' => 1],
            ['title' => 'Avaliação', 'description' => 'Anamnese e metas.', 'image_slug' => 'shop', 'category' => 'Treino', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('xhybrid', [
        'hero' => 'Academia', 'about' => 'Treino', 'landing' => 'Musculação', 'corporate' => 'Personal', 'shop' => 'Aulas', 'maintenance' => 'Resultados',
    ]);
    return $pack;
}

function preset_oficina(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Oficina Mecânica',
        'brand_tagline' => 'Manutenção com confiança',
        'brand_seo_title' => 'Oficina — mecânica e diagnóstico',
        'appearance_look' => 'copper-heat',
        'appearance_theme' => 'cobre',
        'appearance_font' => 'condensed',
        'appearance_layout' => 'frame',
        'appearance_media' => 'classic',
        'whatsapp_message' => 'Olá! Preciso de orçamento para o veículo.',
        'home_badge' => 'Mecânica',
        'home_hero_title_1' => 'Seu carro,',
        'home_hero_title_2' => 'em boas mãos.',
        'home_hero_text' => 'Revisão, freios, suspensão e diagnóstico eletrônico.',
        'home_feat_1_title' => 'Revisão',
        'home_feat_1_icon' => 'wrench',
        'home_feat_1_text' => 'Checklist completo e peças de qualidade.',
        'home_feat_2_title' => 'Diagnóstico',
        'home_feat_2_icon' => 'cpu',
        'home_feat_2_text' => 'Scanner e análise precisa.',
        'home_feat_3_title' => 'Freios',
        'home_feat_3_icon' => 'shield',
        'home_feat_3_text' => 'Segurança em primeiro lugar.',
        '_services' => [
            ['title' => 'Revisão', 'description' => 'Manutenção preventiva.', 'image_slug' => 'landing', 'category' => 'Oficina', 'active' => 1],
            ['title' => 'Freios', 'description' => 'Pastilhas e sistema.', 'image_slug' => 'corporate', 'category' => 'Oficina', 'active' => 1],
            ['title' => 'Suspensão', 'description' => 'Conforto e estabilidade.', 'image_slug' => 'shop', 'category' => 'Oficina', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('eletricista', [
        'hero' => 'Oficina', 'about' => 'Equipe', 'landing' => 'Revisão', 'corporate' => 'Diagnóstico', 'shop' => 'Freios', 'maintenance' => 'Suspensão',
    ]);
    return $pack;
}

function preset_arquitetura(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Arquitetura & Interiores',
        'brand_tagline' => 'Espaços com intenção',
        'brand_seo_title' => 'Arquiteto — projetos residenciais e comerciais',
        'appearance_look' => 'editorial',
        'appearance_theme' => 'branco',
        'appearance_font' => 'editorial',
        'appearance_layout' => 'editorial',
        'appearance_media' => 'flip',
        'whatsapp_message' => 'Olá! Quero orçamento de projeto de arquitetura.',
        'home_badge' => 'Arquitetura',
        'home_hero_title_1' => 'Projetos que',
        'home_hero_title_2' => 'contam histórias.',
        'home_hero_text' => 'Residencial, comercial e interiores com acompanhamento de obra.',
        'home_feat_1_title' => 'Projeto',
        'home_feat_1_icon' => 'layout',
        'home_feat_1_text' => 'Plantas e detalhamento técnico.',
        'home_feat_2_title' => 'Interiores',
        'home_feat_2_icon' => 'home',
        'home_feat_2_text' => 'Ambientes funcionais e elegantes.',
        'home_feat_3_title' => 'Obra',
        'home_feat_3_icon' => 'wrench',
        'home_feat_3_text' => 'Acompanhamento até a entrega.',
        '_services' => [
            ['title' => 'Projeto residencial', 'description' => 'Do briefing à planta.', 'image_slug' => 'landing', 'category' => 'Projetos', 'active' => 1],
            ['title' => 'Interiores', 'description' => 'Ambientes sob medida.', 'image_slug' => 'corporate', 'category' => 'Projetos', 'active' => 1],
            ['title' => 'Comercial', 'description' => 'Lojas e escritórios.', 'image_slug' => 'shop', 'category' => 'Projetos', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('xhybrid', [
        'hero' => 'Projeto', 'about' => 'Estúdio', 'landing' => 'Residencial', 'corporate' => 'Interiores', 'shop' => 'Comercial', 'maintenance' => 'Detalhe',
    ]);
    return $pack;
}

function preset_consultoria(): array
{
    $pack = preset_niche_base([
        'brand_name' => 'Consultoria Empresarial',
        'brand_tagline' => 'Estratégia com clareza',
        'brand_seo_title' => 'Consultoria — negócios e gestão',
        'appearance_look' => 'ash-glass',
        'appearance_theme' => 'slate',
        'appearance_font' => 'saas',
        'appearance_layout' => 'compact',
        'appearance_media' => 'stack-media',
        'whatsapp_message' => 'Olá! Quero conversar sobre consultoria.',
        'home_badge' => 'Consultoria',
        'home_hero_title_1' => 'Decisões',
        'home_hero_title_2' => 'com método.',
        'home_hero_text' => 'Diagnóstico, processos e crescimento para empresas.',
        'home_feat_1_title' => 'Diagnóstico',
        'home_feat_1_icon' => 'search',
        'home_feat_1_text' => 'Mapeamento de gargalos e oportunidades.',
        'home_feat_2_title' => 'Processos',
        'home_feat_2_icon' => 'layers',
        'home_feat_2_text' => 'Organização e eficiência operacional.',
        'home_feat_3_title' => 'Crescimento',
        'home_feat_3_icon' => 'chart',
        'home_feat_3_text' => 'Plano de ação mensurável.',
        '_services' => [
            ['title' => 'Diagnóstico', 'description' => 'Análise inicial do negócio.', 'image_slug' => 'landing', 'category' => 'Consultoria', 'active' => 1],
            ['title' => 'Processos', 'description' => 'Otimização operacional.', 'image_slug' => 'corporate', 'category' => 'Consultoria', 'active' => 1],
            ['title' => 'Mentoria', 'description' => 'Acompanhamento contínuo.', 'image_slug' => 'shop', 'category' => 'Consultoria', 'active' => 1],
        ],
    ]);
    $pack['images'] = preset_media_pack('advocacia', [
        'hero' => 'Reunião', 'about' => 'Equipe', 'landing' => 'Diagnóstico', 'corporate' => 'Processos', 'shop' => 'Plano', 'maintenance' => 'Resultados',
    ]);
    return $pack;
}

function preset_apply(PDO $pdo, string $id): string
{
    require_once __DIR__ . '/settings.php';
    require_once __DIR__ . '/services.php';
    require_once __DIR__ . '/images.php';

    $map = preset_function_map();
    if (!isset($map[$id])) {
        throw new InvalidArgumentException('Preset desconhecido.');
    }
    $fn = $map[$id];
    $preset = $fn();

    settings_save_many($pdo, $preset['settings']);
    services_replace_all($pdo, $preset['services']);
    if (!empty($preset['images']) && is_array($preset['images'])) {
        images_upsert_by_slug($pdo, $preset['images']);
        $keep = [];
        foreach ($preset['images'] as $row) {
            if (!empty($row['slug'])) {
                $keep[] = (string) $row['slug'];
            }
        }
        images_deactivate_unlisted($pdo, $keep);
    }
    return $id;
}

