<?php

declare(strict_types=1);

/**
 * Presets de nicho — aplicam textos, seções, look e serviços de uma vez.
 */
/**
 * Vitrine da agência Xhybrid (Signature + textos tech).
 */
function preset_xhybrid(): array
{
    return [
        'settings' => [
            'brand_name' => 'Xhybrid',
            'brand_tagline' => 'Sites, manutenção e tecnologia',
            'brand_city' => '',
            'brand_seo_title' => 'Xhybrid — Criação de sites, manutenção e tecnologia',
            'brand_seo_description' => 'Agência Xhybrid: criação de sites, manutenção e tecnologia para empresas. Orçamento rápido pelo WhatsApp.',
            'area_text' => '',
            'urgency_enabled' => '0',
            'urgency_label' => '24h',
            'section_hero' => '1',
            'section_features' => '1',
            'section_works' => '1',
            'section_area' => '0',
            'section_testimonials' => '0',
            'section_faq' => '0',
            'section_cta' => '1',
            'appearance_look' => 'xhybrid-signature',
            'appearance_theme' => 'preto',
            'appearance_font' => 'saas',
            'appearance_layout' => 'soft',
            'appearance_media' => 'classic',
            'whatsapp_message' => 'Olá! Vim pelo site da Xhybrid e quero um orçamento de site.',
            'email' => 'contato@xhybrid.com.br',
            'instagram_url' => 'https://instagram.com/xhybrid',
            'instagram_label' => '@xhybrid — projetos e bastidores',
            'nav_index' => 'Início',
            'nav_sobre' => 'Sobre',
            'nav_galeria' => 'Projetos',
            'nav_contato' => 'Contato',
            'footer_tagline' => 'Agência de criação de sites, manutenção e tecnologia — presença digital profissional para o seu negócio.',
            'footer_link_sobre' => 'Sobre nós',
            'fab_label' => 'Fale conosco',
            'footer_hours_title' => 'Horário de funcionamento',
            'footer_hours_line1' => 'Segunda a sexta: 9h – 18h',
            'footer_hours_line2' => 'Sábado: 9h – 13h',
            'footer_hours_line3' => 'Domingo: fechado',
            'home_badge' => 'Sites & tecnologia',
            'home_hero_title_1' => 'Seu negócio,',
            'home_hero_title_2' => 'online de verdade.',
            'home_hero_text' => 'Somos a Xhybrid — criação de sites, manutenção e tecnologia para empresas que querem presença digital profissional.',
            'home_btn_gallery' => 'Ver projetos',
            'home_btn_quote' => 'Pedir orçamento',
            'home_weave_title' => 'O que fazemos',
            'home_weave_subtitle' => 'Do site institucional à manutenção contínua — tecnologia sob medida para o seu negócio.',
            'home_feat_1_title' => 'Criação de sites',
            'home_feat_1_text' => 'Landing pages e sites corporativos modernos, rápidos e alinhados à sua marca.',
            'home_feat_2_title' => 'Manutenção',
            'home_feat_2_text' => 'Atualizações, backups, performance e correções para o site ficar sempre no ar.',
            'home_feat_3_title' => 'Tecnologia',
            'home_feat_3_text' => 'Integrações, automações e melhorias digitais para otimizar o dia a dia.',
            'home_destaques_title' => 'Projetos em destaque',
            'home_destaques_subtitle' => 'Alguns trabalhos de criação e desenvolvimento.',
            'home_destaques_link' => 'Ver portfólio completo',
            'home_cta_title_1' => 'Tem um projeto?',
            'home_cta_title_2' => 'A gente desenvolve.',
            'home_cta_text' => 'Conte o que precisa — site novo, manutenção ou melhoria tecnológica — e montamos a melhor proposta.',
            'home_cta_btn' => 'Chamar no WhatsApp',
            'about_eyebrow' => 'About us',
            'about_title_1' => 'Tecnologia,',
            'about_title_2' => 'com clareza.',
            'about_p1' => 'A Xhybrid nasceu para ajudar empresas a terem presença digital profissional: sites bem feitos, manutenção confiável e tecnologia aplicada ao negócio.',
            'about_p2' => 'Cuidamos do visual, da performance e da operação — do primeiro briefing à publicação, com comunicação direta e prazos claros.',
            'about_p3' => 'Mais do que páginas no ar, entregamos uma base digital sólida para você atender clientes, divulgar serviços e crescer online.',
            'about_btn' => 'Ver projetos',
            'about_stat_1_value' => '100%',
            'about_stat_1_text' => 'Foco em entrega e resultado',
            'about_stat_2_value' => 'Ágil',
            'about_stat_2_text' => 'Processo claro do briefing à publicação',
            'about_stat_3_value' => 'Sob medida',
            'about_stat_3_text' => 'Soluções alinhadas ao seu negócio',
            'gallery_eyebrow' => 'Portfolio',
            'gallery_title' => 'Projetos',
            'gallery_subtitle' => 'Sites e soluções que já entregamos. Toque em uma foto para ampliar.',
            'contact_eyebrow' => 'Get in touch',
            'contact_title' => 'Contato',
            'contact_subtitle' => 'Orçamentos e dúvidas — escolha o canal que preferir.',
            'contact_form_title' => 'Escreva para nós',
            'contact_form_intro' => 'Preencha abaixo e sua mensagem abre direto no seu e-mail.',
            'contact_form_btn' => 'Enviar mensagem',
            'contact_whatsapp_desc' => 'O jeito mais rápido de pedir um orçamento',
            'contact_response_title' => 'Tempo de resposta',
            'contact_response_text' => 'Respondemos em até 1 dia útil',
            'testimonials_title' => 'O que dizem os clientes',
            'testimonial_1_name' => '',
            'testimonial_1_city' => '',
            'testimonial_1_text' => '',
            'testimonial_2_name' => '',
            'testimonial_2_city' => '',
            'testimonial_2_text' => '',
            'testimonial_3_name' => '',
            'testimonial_3_city' => '',
            'testimonial_3_text' => '',
            'faq_title' => 'Dúvidas frequentes',
            'faq_1_q' => '',
            'faq_1_a' => '',
            'faq_2_q' => '',
            'faq_2_a' => '',
            'faq_3_q' => '',
            'faq_3_a' => '',
            'faq_4_q' => '',
            'faq_4_a' => '',
        ],
        'services' => [
            [
                'title' => 'Landing Page',
                'description' => 'Página de captura rápida, objetiva e otimizada para conversão.',
                'image_slug' => 'amigurumi',
                'category' => 'Criação',
                'active' => 1,
            ],
            [
                'title' => 'Site Corporativo',
                'description' => 'Site institucional moderno para apresentar empresa, serviços e contato.',
                'image_slug' => 'manta',
                'category' => 'Criação',
                'active' => 1,
            ],
            [
                'title' => 'Manutenção contínua',
                'description' => 'Atualizações, backups, performance e suporte para o site ficar no ar.',
                'image_slug' => 'sousplat',
                'category' => 'Manutenção',
                'active' => 1,
            ],
            [
                'title' => 'Integrações',
                'description' => 'WhatsApp, formulários, CRM e automações alinhadas ao seu fluxo.',
                'image_slug' => 'top',
                'category' => 'Tecnologia',
                'active' => 1,
            ],
        ],
    ];
}

function preset_eletricista(): array
{
    return [
        'settings' => [
            'brand_name' => 'Eletricista Pro',
            'brand_tagline' => 'Elétrica residencial e predial',
            'brand_city' => 'Sua cidade',
            'brand_seo_title' => 'Eletricista em Sua cidade — residencial, predial e emergência',
            'brand_seo_description' => 'Serviços elétricos com segurança e agilidade. Orçamento rápido pelo WhatsApp.',
            'area_text' => 'Atendo bairros e cidades da região — consulte disponibilidade.',
            'urgency_enabled' => '1',
            'urgency_label' => '24h',
            'section_hero' => '1',
            'section_features' => '1',
            'section_works' => '1',
            'section_area' => '1',
            'section_testimonials' => '1',
            'section_faq' => '1',
            'section_cta' => '1',
            'appearance_look' => 'azure-blast',
            'appearance_theme' => 'azul',
            'appearance_font' => 'geometric',
            'appearance_layout' => 'frame',
            'appearance_media' => 'media-wide',
            'whatsapp_message' => 'Olá! Preciso de um eletricista. Vim pelo site.',
            'nav_index' => 'Início',
            'nav_sobre' => 'Sobre',
            'nav_galeria' => 'Serviços',
            'nav_contato' => 'Contato',
            'footer_tagline' => 'Elétrica residencial e predial com segurança, clareza e atendimento rápido.',
            'footer_link_sobre' => 'Quem somos',
            'fab_label' => 'Chamar agora',
            'footer_hours_title' => 'Atendimento',
            'footer_hours_line1' => 'Segunda a sábado: 8h – 20h',
            'footer_hours_line2' => 'Emergências: consulte no WhatsApp',
            'footer_hours_line3' => 'Domingo: sob demanda',
            'home_badge' => 'Eletricista profissional',
            'home_hero_title_1' => 'Elétrica segura',
            'home_hero_title_2' => 'quando você precisa.',
            'home_hero_text' => 'Instalações, manutenção e emergências com atendimento ágil. Peça orçamento pelo WhatsApp.',
            'home_btn_gallery' => 'Ver serviços',
            'home_btn_quote' => 'Orçamento no WhatsApp',
            'home_weave_title' => 'O que faço',
            'home_weave_subtitle' => 'Soluções elétricas para casa, comércio e condomínio — com padrão de segurança.',
            'home_feat_1_title' => 'Instalações',
            'home_feat_1_text' => 'Quadros, tomadas, iluminação e projetos elétricos residenciais e prediais.',
            'home_feat_2_title' => 'Manutenção',
            'home_feat_2_text' => 'Revisão, troca de disjuntores, curto-circuito e melhorias de segurança.',
            'home_feat_3_title' => 'Emergência',
            'home_feat_3_text' => 'Atendimento urgente para falta de energia, cheiro de queimado e riscos.',
            'home_destaques_title' => 'Trabalhos recentes',
            'home_destaques_subtitle' => 'Alguns serviços realizados em campo.',
            'home_destaques_link' => 'Ver mais fotos',
            'home_cta_title_1' => 'Precisa de eletricista?',
            'home_cta_title_2' => 'Chame agora.',
            'home_cta_text' => 'Conte o problema e a região — respondo rápido com orientação e orçamento.',
            'home_cta_btn' => 'WhatsApp',
            'about_eyebrow' => 'Sobre',
            'about_title_1' => 'Trabalho sério,',
            'about_title_2' => 'sem improviso.',
            'about_p1' => 'Atendo elétrica residencial e predial com foco em segurança, organização e comunicação clara.',
            'about_p2' => 'Explico o que será feito, materiais necessários e prazo — sem surpresas no meio do serviço.',
            'about_p3' => 'Se precisa de instalação, manutenção ou emergência, fale comigo pelo WhatsApp.',
            'about_btn' => 'Ver serviços',
            'about_stat_1_value' => 'Segurança',
            'about_stat_1_text' => 'Padrão técnico em cada serviço',
            'about_stat_2_value' => 'Ágil',
            'about_stat_2_text' => 'Resposta rápida pelo WhatsApp',
            'about_stat_3_value' => 'Local',
            'about_stat_3_text' => 'Atendimento na sua região',
            'gallery_eyebrow' => 'Serviços',
            'gallery_title' => 'Galeria',
            'gallery_subtitle' => 'Fotos de serviços e instalações. Toque para ampliar.',
            'contact_eyebrow' => 'Contato',
            'contact_title' => 'Fale comigo',
            'contact_subtitle' => 'Orçamento e emergência — WhatsApp é o canal mais rápido.',
            'contact_form_title' => 'Envie uma mensagem',
            'contact_form_intro' => 'Preencha e a mensagem abre no seu e-mail.',
            'contact_form_btn' => 'Enviar',
            'contact_whatsapp_desc' => 'Melhor canal para orçamento e urgência',
            'contact_response_title' => 'Tempo de resposta',
            'contact_response_text' => 'Respondo o mais rápido possível no horário de atendimento',
            'testimonials_title' => 'Clientes satisfeitos',
            'testimonial_1_name' => 'Ana Paula',
            'testimonial_1_city' => 'Centro',
            'testimonial_1_text' => 'Resolveu o quadro elétrico no mesmo dia. Atendimento claro e limpo.',
            'testimonial_2_name' => 'Carlos',
            'testimonial_2_city' => 'Jardins',
            'testimonial_2_text' => 'Instalou a iluminação da casa com muito cuidado. Recomendo.',
            'testimonial_3_name' => 'Marina',
            'testimonial_3_city' => 'Vila Nova',
            'testimonial_3_text' => 'Veio rápido na emergência e explicou tudo sem enrolação.',
            'faq_title' => 'Dúvidas frequentes',
            'faq_1_q' => 'Atende emergência?',
            'faq_1_a' => 'Sim — conforme disponibilidade. Chame no WhatsApp informando o bairro e o problema.',
            'faq_2_q' => 'Emite nota / recibo?',
            'faq_2_a' => 'Combinamos a forma de pagamento e documentação no orçamento.',
            'faq_3_q' => 'Quais bairros atende?',
            'faq_3_a' => 'Atendo a região informada no site. Se estiver em dúvida, pergunte no WhatsApp.',
            'faq_4_q' => 'Tem garantia do serviço?',
            'faq_4_a' => 'Sim, os serviços têm garantia combinada conforme o tipo de trabalho.',
        ],
        'services' => [
            [
                'title' => 'Instalação residencial',
                'description' => 'Tomadas, iluminação, chuveiro e padrões com segurança.',
                'image_slug' => 'amigurumi',
                'category' => 'Residencial',
                'active' => 1,
            ],
            [
                'title' => 'Quadro elétrico',
                'description' => 'Montagem, troca de disjuntores e organização do quadro.',
                'image_slug' => 'manta',
                'category' => 'Segurança',
                'active' => 1,
            ],
            [
                'title' => 'Manutenção predial',
                'description' => 'Revisão e correções para condomínios e comércios.',
                'image_slug' => 'sousplat',
                'category' => 'Predial',
                'active' => 1,
            ],
            [
                'title' => 'Emergência',
                'description' => 'Falta de energia, curto-circuito e riscos elétricos.',
                'image_slug' => 'top',
                'category' => 'Urgência',
                'active' => 1,
            ],
            [
                'title' => 'Iluminação LED',
                'description' => 'Projetos e troca para economia e melhor luz.',
                'image_slug' => 'bolsa',
                'category' => 'Iluminação',
                'active' => 1,
            ],
            [
                'title' => 'Padrão / entrada',
                'description' => 'Adequação de padrão e entrada de energia.',
                'image_slug' => 'bebe',
                'category' => 'Residencial',
                'active' => 1,
            ],
        ],
    ];
}

function preset_apply(PDO $pdo, string $id): string
{
    require_once __DIR__ . '/settings.php';
    require_once __DIR__ . '/services.php';

    if ($id === 'xhybrid') {
        $preset = preset_xhybrid();
    } elseif ($id === 'eletricista') {
        $preset = preset_eletricista();
    } else {
        throw new InvalidArgumentException('Preset desconhecido.');
    }

    settings_save_many($pdo, $preset['settings']);
    services_replace_all($pdo, $preset['services']);
    return $id;
}
